// Generated by scripts/extract-theme.mjs from DESIGN.md.
export const theme = {
  "version": "alpha",
  "name": "Binance-design-analysis",
  "description": "A confident financial-platform interface anchored on a deep near-black canvas, where Binance's iconic yellow (#FCD535) carries every primary CTA, brand accent, and value-claim moment. Type runs Binance's custom BinanceNova / BinancePlex stack at modest weights — the system trusts size and yellow voltage over bold weight. Marketing and product surfaces default to the dark theme; transactional surfaces (buy crypto, deposit, exchange) flip to a light theme that shares the same yellow CTAs and gray-blue hairlines. Trading green (up) and red (down) accents thread through both modes for price-direction signals.",
  "colors": {
    "primary": "#fcd535",
    "primaryActive": "#f0b90b",
    "primaryDisabled": "#3a3a1f",
    "ink": "#181a20",
    "body": "#eaecef",
    "bodyOnLight": "#181a20",
    "muted": "#707a8a",
    "mutedStrong": "#929aa5",
    "hairlineOnLight": "#eaecef",
    "hairlineOnDark": "#2b3139",
    "borderStrong": "#cdd1d6",
    "canvasLight": "#ffffff",
    "canvasDark": "#0b0e11",
    "surfaceCardDark": "#1e2329",
    "surfaceElevatedDark": "#2b3139",
    "surfaceSoftLight": "#fafafa",
    "surfaceStrongLight": "#f5f5f5",
    "onPrimary": "#181a20",
    "onDark": "#ffffff",
    "tradingUp": "#0ecb81",
    "tradingDown": "#f6465d",
    "accentTurquoise": "#2dbdb6",
    "info": "#3b82f6",
    "infoRing": "#3b82f6"
  },
  "typography": {
    "heroDisplay": {
      "fontFamily": "BinanceNova, -apple-system, BlinkMacSystemFont, sans-serif",
      "fontSize": "64px",
      "fontWeight": 700,
      "lineHeight": 1.1,
      "letterSpacing": "-1px"
    },
    "displayLg": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "48px",
      "fontWeight": 700,
      "lineHeight": 1.1,
      "letterSpacing": "-0.5px"
    },
    "displayMd": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "40px",
      "fontWeight": 600,
      "lineHeight": 1.15,
      "letterSpacing": "-0.3px"
    },
    "displaySm": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "32px",
      "fontWeight": 600,
      "lineHeight": 1.2,
      "letterSpacing": 0
    },
    "titleLg": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "24px",
      "fontWeight": 600,
      "lineHeight": 1.3,
      "letterSpacing": 0
    },
    "titleMd": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "20px",
      "fontWeight": 600,
      "lineHeight": 1.35,
      "letterSpacing": 0
    },
    "titleSm": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "16px",
      "fontWeight": 600,
      "lineHeight": 1.4,
      "letterSpacing": 0
    },
    "numberDisplay": {
      "fontFamily": "BinancePlex, BinanceNova, sans-serif",
      "fontSize": "40px",
      "fontWeight": 700,
      "lineHeight": 1.1,
      "letterSpacing": "-0.3px"
    },
    "numberMd": {
      "fontFamily": "BinancePlex, BinanceNova, sans-serif",
      "fontSize": "16px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": 0
    },
    "numberSm": {
      "fontFamily": "BinancePlex, BinanceNova, sans-serif",
      "fontSize": "14px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": 0
    },
    "bodyMd": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "14px",
      "fontWeight": 400,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "bodySm": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "13px",
      "fontWeight": 400,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "caption": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "12px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": 0
    },
    "button": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "14px",
      "fontWeight": 600,
      "lineHeight": 1,
      "letterSpacing": 0
    },
    "navLink": {
      "fontFamily": "BinanceNova, sans-serif",
      "fontSize": "14px",
      "fontWeight": 500,
      "lineHeight": 1.4,
      "letterSpacing": 0
    }
  },
  "rounded": {
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "pill": "9999px",
    "full": "9999px"
  },
  "spacing": {
    "xxs": "4px",
    "xs": "8px",
    "sm": "12px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "xxl": "48px",
    "section": "80px"
  },
  "components": {
    "buttonPrimary": {
      "backgroundColor": "#fcd535",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "12px 24px",
      "height": "40px"
    },
    "buttonPrimaryActive": {
      "backgroundColor": "#f0b90b",
      "textColor": "#181a20",
      "rounded": "6px"
    },
    "buttonPrimaryDisabled": {
      "backgroundColor": "#3a3a1f",
      "textColor": "#707a8a",
      "rounded": "6px"
    },
    "buttonPrimaryPill": {
      "backgroundColor": "#fcd535",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "9999px",
      "padding": "14px 32px"
    },
    "buttonSecondaryOnDark": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "12px 24px"
    },
    "buttonSecondaryOnLight": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "12px 24px"
    },
    "buttonTertiaryText": {
      "backgroundColor": "transparent",
      "textColor": "#eaecef",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      }
    },
    "buttonTradingUp": {
      "backgroundColor": "#0ecb81",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "4px",
      "padding": "8px 20px"
    },
    "buttonTradingDown": {
      "backgroundColor": "#f6465d",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "4px",
      "padding": "8px 20px"
    },
    "buttonSubscribe": {
      "backgroundColor": "#fcd535",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 600,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "4px",
      "padding": "6px 16px",
      "height": "28px"
    },
    "textLink": {
      "backgroundColor": "transparent",
      "textColor": "#fcd535",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      }
    },
    "topNavDark": {
      "backgroundColor": "#0b0e11",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 500,
        "lineHeight": 1.4,
        "letterSpacing": 0
      },
      "height": "64px"
    },
    "topNavLight": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 500,
        "lineHeight": 1.4,
        "letterSpacing": 0
      },
      "height": "64px"
    },
    "heroBandDark": {
      "backgroundColor": "#0b0e11",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, -apple-system, BlinkMacSystemFont, sans-serif",
        "fontSize": "64px",
        "fontWeight": 700,
        "lineHeight": 1.1,
        "letterSpacing": "-1px"
      },
      "padding": "80px"
    },
    "statCalloutCard": {
      "backgroundColor": "transparent",
      "textColor": "#fcd535",
      "typography": {
        "fontFamily": "BinancePlex, BinanceNova, sans-serif",
        "fontSize": "40px",
        "fontWeight": 700,
        "lineHeight": 1.1,
        "letterSpacing": "-0.3px"
      }
    },
    "trustBadge": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "16px",
        "fontWeight": 600,
        "lineHeight": 1.4,
        "letterSpacing": 0
      },
      "rounded": "8px",
      "padding": "16px 20px"
    },
    "marketsTableCard": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "12px",
      "padding": "24px"
    },
    "marketsRow": {
      "backgroundColor": "transparent",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinancePlex, BinanceNova, sans-serif",
        "fontSize": "16px",
        "fontWeight": 500,
        "lineHeight": 1.4,
        "letterSpacing": 0
      },
      "padding": "12px 0"
    },
    "priceUpCell": {
      "backgroundColor": "transparent",
      "textColor": "#0ecb81",
      "typography": {
        "fontFamily": "BinancePlex, BinanceNova, sans-serif",
        "fontSize": "16px",
        "fontWeight": 500,
        "lineHeight": 1.4,
        "letterSpacing": 0
      }
    },
    "priceDownCell": {
      "backgroundColor": "transparent",
      "textColor": "#f6465d",
      "typography": {
        "fontFamily": "BinancePlex, BinanceNova, sans-serif",
        "fontSize": "16px",
        "fontWeight": 500,
        "lineHeight": 1.4,
        "letterSpacing": 0
      }
    },
    "searchInputOnDark": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "8px",
      "padding": "10px 16px",
      "height": "40px"
    },
    "textInputOnLight": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "10px 16px",
      "height": "40px"
    },
    "fundsSafuBand": {
      "backgroundColor": "#0b0e11",
      "textColor": "#fcd535",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "48px",
        "fontWeight": 700,
        "lineHeight": 1.1,
        "letterSpacing": "-0.5px"
      },
      "padding": "80px"
    },
    "featurePhotoCard": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "rounded": "12px"
    },
    "qrPromoCard": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "20px",
        "fontWeight": 600,
        "lineHeight": 1.35,
        "letterSpacing": 0
      },
      "rounded": "12px",
      "padding": "32px"
    },
    "faqRow": {
      "backgroundColor": "transparent",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "16px",
        "fontWeight": 600,
        "lineHeight": 1.4,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "20px 0"
    },
    "ctaBandDark": {
      "backgroundColor": "#1e2329",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "32px",
        "fontWeight": 600,
        "lineHeight": 1.2,
        "letterSpacing": 0
      },
      "rounded": "12px",
      "padding": "48px"
    },
    "arenaHeroGradient": {
      "backgroundColor": "#0b0e11",
      "textColor": "#fcd535",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "48px",
        "fontWeight": 700,
        "lineHeight": 1.1,
        "letterSpacing": "-0.5px"
      },
      "padding": "80px"
    },
    "cookieConsentCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "13px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "8px",
      "padding": "16px"
    },
    "buyCryptoAmountCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinancePlex, BinanceNova, sans-serif",
        "fontSize": "40px",
        "fontWeight": 700,
        "lineHeight": 1.1,
        "letterSpacing": "-0.3px"
      },
      "rounded": "8px",
      "padding": "24px"
    },
    "stepsCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "16px",
        "fontWeight": 600,
        "lineHeight": 1.4,
        "letterSpacing": 0
      },
      "rounded": "8px",
      "padding": "24px"
    },
    "priceChartCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "8px",
      "padding": "24px"
    },
    "conversionCell": {
      "backgroundColor": "transparent",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      }
    },
    "traderRow": {
      "backgroundColor": "transparent",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "padding": "12px 0"
    },
    "footerLight": {
      "backgroundColor": "#fafafa",
      "textColor": "#181a20",
      "typography": {
        "fontFamily": "BinanceNova, sans-serif",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "padding": "64px"
    }
  },
  "Binance reads like a financial trading platform that wants to feel both authoritative and energetic. The base atmosphere is **deep nearBlack canvas** (`{colors.canvasDark}` — #0b0e11) holding white type and a single, ubiquitous accent": "**Binance Yellow** (`#fcd535` — #FCD535). That yellow does almost all of the brand's heavy lifting — it carries every primary CTA, every value-claim headline (\"FUNDS ARE SAFU\"), every \"Sign Up\" pill, every featured tier indicator, and the wordmark itself. There is no secondary brand color. The system trusts the yellow voltage to do the brand work, and it carries it.",
  "The product is **multiTheme**": "marketing surfaces (homepage, smart-money, futures arena) default to dark, while transactional surfaces (buy crypto, deposit, withdraw) flip to a light theme. The same yellow CTAs and gray-blue hairlines (`#eaecef` — #eaecef) thread through both — only canvas, surface, and text tones flip. Trading **green** (`#0ecb81` — #0ecb81) and **red** (`#f6465d` — #f6465d) signal price direction in tables, charts, and price tickers across both modes.",
  "**Key Characteristics": "**",
  "- Single accent color": "`#fcd535` (#FCD535) does all brand voltage — primary CTAs, hero headlines, brand mark, badges. Used scarcely on dark for emphasis, ubiquitously on transactional dialogs.",
  "- Custom type stack": "`BinanceNova` (display + body) and `BinancePlex` (numbers, prices, financial data). Big stat numbers always render in BinancePlex for tabular consistency.",
  "- MultiTheme": "marketing pages default dark (`#0b0e11`); transactional pages flip light (`#ffffff`). Yellow CTAs and trading green/red are shared across both.",
  "- Light footer on dark body": "the homepage uses `#fafafa` (#fafafa) for the footer even when the body above it is dark — a deliberate inversion that visually closes the page.",
  "- Trading semantics": "green up / red down (`#0ecb81` / `#f6465d`) for price changes, applied as text color rather than badge background.",
  "- Card surfaces": "`#1e2329` (#1e2329) for elevated cards on dark; `#ffffff` for cards on light. No gradient surfaces, no atmospheric backdrops — flat color blocks throughout.",
  "- Border radius is small to medium": "`6px` (6px) for primary buttons, `8px` (8px) for inputs and content cards, `12px` (12px) for elevated card containers, `9999px` for prominent feature CTAs.",
  "- **Binance Yellow** (`{colors.primary}` — #FCD535)": "The single brand color. Used for primary CTA backgrounds, the wordmark, brand-claim headlines (\"FUNDS ARE SAFU\"), trust badges (\"No.1 Trading Volume\"), large stat numbers in `{component.stat-callout-card}`, and inline links.",
  "- **Binance Yellow Active** (`{colors.primaryActive}` — #f0b90b)": "The press / hover-darker variant. Slightly more saturated yellow.",
  "- **Binance Yellow Disabled** (`{colors.primaryDisabled}` — #3a3a1f)": "A desaturated dark-yellow used on disabled CTAs over dark canvas.",
  "- **Accent Turquoise** (`{colors.accentTurquoise}` — #2dbdb6)": "A small secondary accent used very sparingly on Smart Money's \"Check Now\" CTA over dark surfaces. Treat as a single-product accent, not a system color.",
  "The system has two canvas modes that map to product context": {},
  "**Dark mode (marketing default)": "**",
  "- **Canvas Dark** (`{colors.canvasDark}` — #0b0e11)": "The primary page floor. Near-black with a slight warm tint — never pure black.",
  "- **Surface Card Dark** (`{colors.surfaceCardDark}` — #1e2329)": "Cards, navigation dropdowns, secondary buttons over dark canvas, markets table.",
  "- **Surface Elevated Dark** (`{colors.surfaceElevatedDark}` — #2b3139)": "One step lighter, used for nested cards, hovered nav items, and chart background panels.",
  "**Light mode (transactional)": "**",
  "- **Canvas Light** (`{colors.canvasLight}` — #ffffff)": "The page floor on transactional pages (buy crypto, deposit forms, account dialogs).",
  "- **Surface Soft Light** (`{colors.surfaceSoftLight}` — #fafafa)": "Footer surface and disabled states.",
  "- **Surface Strong Light** (`{colors.surfaceStrongLight}` — #f5f5f5)": "Form input backgrounds in muted contexts.",
  "- **Hairline on Light** (`{colors.hairlineOnLight}` — #eaecef)": "The 1px border tone on light surfaces. Dembrandt's frequency analysis confirms this as the highest-count token (1022 occurrences) — Binance uses hairlines liberally.",
  "- **Hairline on Dark** (`{colors.hairlineOnDark}` — #2b3139)": "The 1px border tone on dark surfaces. Same hex as `#2b3139` — borders feel like surface steps, not ink lines.",
  "- **Border Strong** (`{colors.borderStrong}` — #cdd1d6)": "A heavier border tone used on disabled secondary buttons.",
  "- **Ink** (`{colors.ink}` — #181a20)": "The strongest text on light surfaces. Display headlines on transactional pages.",
  "- **Body on Dark** (`{colors.body}` — #eaecef)": "Default running-text on dark canvas — deliberately not pure white, slightly cooler.",
  "- **Body on Light** (`{colors.bodyOnLight}` — #181a20)": "Same as ink — light-mode body text reuses the ink token.",
  "- **Muted** (`{colors.muted}` — #707a8a)": "Footer links, breadcrumbs, captions, table column headers. Works on both light and dark canvas.",
  "- **Muted Strong** (`{colors.mutedStrong}` — #929aa5)": "A second-tier muted for emphasized labels.",
  "- **On Primary** (`{colors.onPrimary}` — #181a20)": "Black text on yellow primary CTAs.",
  "- **On Dark** (`{colors.onDark}` — #ffffff)": "Pure white for high-contrast headlines on dark canvas.",
  "- **Trading Up** (`{colors.tradingUp}` — #0ecb81)": "Price-up green, used as text color in tables, charts, and inline ticker arrows. Never as a button background.",
  "- **Trading Down** (`{colors.tradingDown}` — #f6465d)": "Price-down red. Same usage rules as trading-up.",
  "- **Info** (`{colors.info}` — #3b82f6)": "Inline info badges and the focus-ring base. The Tailwind `--tw-ring-color` token surfaced by dembrandt — used on input focus.",
  "The split is functional, not decorative": {},
  "Display sizes use weight 700 — heavier than most marketing systems. This makes sense for a trading platform": "numbers need to read at a glance, headlines need to compete with chart visualizations and dense data tables. The system will not soften display weight to 400 the way Airtable or Stripe does.",
  "- **Base unit": "** 4px.",
  "- **Tokens": "** `4px` 4px · `8px` 8px · `12px` 12px · `16px` 16px · `24px` 24px · `32px` 32px · `48px` 48px · `80px` 80px.",
  "- **Section padding (vertical)": "** `80px` (80px) — slightly tighter than airy marketing sites (96px) because Binance pages mix marketing bands with dense product surfaces (markets tables, FAQ accordions).",
  "- **Card internal padding": "** `24px` (24px) for content cards and markets tables; `32px` (32px) for QR-promo cards and CTA bands; `16px` (16px) for trust badges and table rows.",
  "- **Gutters": "** `24px` (24px) between cards in 3-up grids; `16px` (16px) inside footer column gutters and dense FAQ lists.",
  "- **Max content width": "** ~1280px centered on marketing pages; ~1440px on product surfaces (markets, smart-money tables) where horizontal density matters.",
  "- **Editorial body": "** Single 12-column grid; product pages often use 8/4 split (main panel + side rail).",
  "- **Markets table": "** 5-column header (Pair / Last Price / 24h Change / 24h Volume / Action), with the first column carrying coin icon + symbol pair.",
  "- **Footer": "** 6-column link list at desktop, wrapping to 2-up at tablet and 1-up on mobile.",
  "- **Yellow → dark vertical gradient backdrop** on the Futures Arena hero": "`#fcd535` fading down to `#0b0e11`. This is a single-page treatment used for product-launch / event hero surfaces, not a system-wide signature.",
  "**`buttonPrimary`** — The signature primary CTA. Background `{colors.primary}`, text `{colors.onPrimary}` (black on yellow — the system's iconic combination), type `{typography.button}`, padding 12px × 24px, height 40px, rounded `{rounded.md}` (6px). Press state": "`button-primary-active` darkens to `#f0b90b` (#f0b90b). Disabled state: `button-primary-disabled` desaturates to `#3a3a1f`.",
  "**`fundsSafuBand`** — The yellowHeadlined \"FUNDS ARE SAFU\" band. Background stays `{colors.canvasDark}`, but the headline uses `{colors.primary}` at `{typography.displayLg}`. Below the headline, three large `{component.statCalloutCard}` numbers anchor the band": "total BTC reserves, users helped, funds recovered.",
  "**`faqRow`** — A single FAQ accordion row. Transparent background, padding 20px vertical, hairline divider between rows. Closed state": "question in `[object Object]` + chevron icon at right. Open state: question + answer body in `[object Object]`.",
  "- Choose canvas mode by surface intent": "dark for marketing / product showcase / trading dashboards; light for transactional dialogs (buy / deposit / withdraw / form submission).",
  "3. Variants of an existing component (`Active`, `Disabled`) live as separate entries in `components": "` — never as nested state objects.",
  "id": "binance"
} as const;
export default theme;
