// Generated by scripts/extract-theme.mjs from DESIGN.md.
export const theme = {
  id: 'clickhouse',
  name: 'ClickHouse-design-analysis',
  colors: {
    primary: '#faff69', primaryActive: '#e6eb52', primaryDisabled: '#3a3a1f', black: '#000000', actionText: '#000000', ink: '#ffffff',
    body: '#cccccc', bodyStrong: '#e6e6e6', muted: '#888888', mutedSoft: '#5a5a5a',
    hairline: '#2a2a2a', hairlineStrong: '#3a3a3a', canvas: '#0a0a0a', surfaceSoft: '#121212',
    surfaceCard: '#1a1a1a', surfaceElevated: '#242424', surfaceYellowBand: '#faff69',
    onPrimary: '#0a0a0a', onDark: '#ffffff', onYellow: '#0a0a0a', accentEmerald: '#22c55e',
    accentRose: '#ef4444', accentBlue: '#3b82f6', success: '#22c55e', warning: '#f59e0b', error: '#ef4444',
  },
  typography: { sans: 'Inter, sans-serif', mono: 'JetBrains Mono, ui-monospace, monospace' },
} as const;
export default theme;
