// Generated by scripts/extract-theme.mjs from DESIGN.md.
export const theme = {
  "version": "alpha",
  "name": "PostHog-design-analysis",
  "description": "|",
  "A playful developerTools system rendered on a warm cream canvas with handDrawn hedgehog mascots dotted across every page like marginalia in a sketchbook. The chrome reads like a friendly engineering blog": "olive-gray ink (#4d4f46) for body, deep olive-charcoal (#23251d) for headlines, IBM Plex Sans Variable typography in tight 1.43-line-height paragraphs, and a single saturated yellow-orange CTA pill (#f7a501) carrying every primary action. The system actively rejects the genre's typical somber dark-tech aesthetic in favor of a creamy, textbook-illustration sensibility — bordered cards stack on the cream canvas with 4–6px radii, doc sidebars use rounded outline-icon mini-illustrations, and the home page leans on cartoon characters (hedgehogs in lab coats, hedgehogs at terminals, hedgehogs in lounge chairs) as its signature decoration. Code samples and product analytics charts live inside white-on-cream cards with thin olive borders; the contrast between the playful illustration and the data-dense product imagery is the brand's signature voice.",
  "colors": {
    "primary": "#f7a501",
    "primaryPressed": "#dd9001",
    "primaryActive": "#b17816",
    "onPrimary": "#23251d",
    "ink": "#23251d",
    "body": "#4d4f46",
    "charcoal": "#33342d",
    "mute": "#6c6e63",
    "ash": "#9b9c92",
    "stone": "#b6b7af",
    "hairline": "#bfc1b7",
    "hairlineSoft": "#dcdfd2",
    "onDark": "#ffffff",
    "canvas": "#eeefe9",
    "surfaceSoft": "#e5e7e0",
    "surfaceCard": "#ffffff",
    "surfaceDoc": "#fcfcfa",
    "surfaceDark": "#23251d",
    "linkBlue": "#1d4ed8",
    "linkTeal": "#1078a3",
    "accentBlue": "#2c84e0",
    "accentBlueSoft": "#dceaf6",
    "accentRed": "#cd4239",
    "accentRedSoft": "#f7d6d3",
    "accentGreen": "#2c8c66",
    "accentGreenSoft": "#d9eddf",
    "accentPurple": "#7c44a6",
    "accentPurpleSoft": "#e7d8ee",
    "focusRing": "rgba(59,130,246,0.5)"
  },
  "typography": {
    "displayXl": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "36px",
      "fontWeight": 700,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "displayLg": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "24px",
      "fontWeight": 800,
      "lineHeight": 1.33,
      "letterSpacing": "-0.6px"
    },
    "headingLg": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "21px",
      "fontWeight": 700,
      "lineHeight": 1.4,
      "letterSpacing": "-0.5px"
    },
    "headingMd": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "20px",
      "fontWeight": 700,
      "lineHeight": 1.4,
      "letterSpacing": 0
    },
    "headingSm": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "18px",
      "fontWeight": 700,
      "lineHeight": 1.5,
      "letterSpacing": 0,
      "textTransform": "uppercase"
    },
    "headingSmMixed": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "18px",
      "fontWeight": 600,
      "lineHeight": 1.56,
      "letterSpacing": 0
    },
    "bodyMd": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "bodyStrong": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "16px",
      "fontWeight": 600,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "bodySm": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "15px",
      "fontWeight": 400,
      "lineHeight": 1.71,
      "letterSpacing": 0
    },
    "bodySmStrong": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "15px",
      "fontWeight": 600,
      "lineHeight": 1.71,
      "letterSpacing": 0
    },
    "bodyXs": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "14px",
      "fontWeight": 500,
      "lineHeight": 1.43,
      "letterSpacing": 0
    },
    "captionMd": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "14px",
      "fontWeight": 700,
      "lineHeight": 1.71,
      "letterSpacing": 0
    },
    "captionSm": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "13px",
      "fontWeight": 500,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "captionXs": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "12px",
      "fontWeight": 600,
      "lineHeight": 1.33,
      "letterSpacing": 0,
      "textTransform": "uppercase"
    },
    "utilityXs": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "12px",
      "fontWeight": 700,
      "lineHeight": 1.33,
      "letterSpacing": 0,
      "textTransform": "uppercase"
    },
    "linkMd": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "buttonMd": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "14px",
      "fontWeight": 700,
      "lineHeight": 1.5,
      "letterSpacing": 0
    },
    "buttonSm": {
      "fontFamily": "IBM Plex Sans Variable",
      "fontSize": "13px",
      "fontWeight": 500,
      "lineHeight": 1,
      "letterSpacing": 0
    },
    "codeSm": {
      "fontFamily": "ui-monospace",
      "fontSize": "14px",
      "fontWeight": 400,
      "lineHeight": 1.43,
      "letterSpacing": 0
    },
    "codeXs": {
      "fontFamily": "Source Code Pro",
      "fontSize": "14px",
      "fontWeight": 500,
      "lineHeight": 1.43,
      "letterSpacing": 0
    }
  },
  "rounded": {
    "none": "0px",
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "full": "9999px"
  },
  "spacing": {
    "xxs": "2px",
    "xs": "4px",
    "sm": "8px",
    "md": "12px",
    "lg": "16px",
    "xl": "24px",
    "xxl": "32px",
    "section": "80px"
  },
  "components": {
    "buttonPrimary": {
      "backgroundColor": "#f7a501",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 700,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "8px 16px",
      "height": "40px"
    },
    "buttonPrimaryPressed": {
      "backgroundColor": "#dd9001",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 700,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px"
    },
    "buttonSecondary": {
      "backgroundColor": "#e5e7e0",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 700,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "8px 16px",
      "height": "40px"
    },
    "buttonTertiary": {
      "backgroundColor": "transparent",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 700,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "8px 12px"
    },
    "buttonDisabled": {
      "backgroundColor": "#e5e7e0",
      "textColor": "#9b9c92",
      "rounded": "6px"
    },
    "textInput": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "8px 12px",
      "height": "36px"
    },
    "textInputFocused": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "rounded": "6px"
    },
    "searchInput": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "8px 12px",
      "height": "36px"
    },
    "productCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "24px"
    },
    "docCard": {
      "backgroundColor": "#fcfcfa",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "24px"
    },
    "featureTile": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "18px",
        "fontWeight": 600,
        "lineHeight": 1.56,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "20px"
    },
    "pricingTierCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "32px"
    },
    "hedgehogMascotCard": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "24px"
    },
    "productTab": {
      "backgroundColor": "transparent",
      "textColor": "#4d4f46",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 600,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "8px 12px"
    },
    "productTabActive": {
      "backgroundColor": "#ffffff",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 600,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px"
    },
    "pillTab": {
      "backgroundColor": "transparent",
      "textColor": "#4d4f46",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "13px",
        "fontWeight": 500,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "9999px",
      "padding": "6px 14px"
    },
    "pillTabActive": {
      "backgroundColor": "#23251d",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "13px",
        "fontWeight": 500,
        "lineHeight": 1,
        "letterSpacing": 0
      },
      "rounded": "9999px"
    },
    "badgeUppercase": {
      "backgroundColor": "transparent",
      "textColor": "#4d4f46",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "12px",
        "fontWeight": 700,
        "lineHeight": 1.33,
        "letterSpacing": 0,
        "textTransform": "uppercase"
      },
      "rounded": "0px"
    },
    "badgePromo": {
      "backgroundColor": "#dceaf6",
      "textColor": "#1d4ed8",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "12px",
        "fontWeight": 600,
        "lineHeight": 1.33,
        "letterSpacing": 0,
        "textTransform": "uppercase"
      },
      "rounded": "9999px",
      "padding": "2px 8px"
    },
    "bannerTipBlue": {
      "backgroundColor": "#dceaf6",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "16px 20px"
    },
    "bannerTipGreen": {
      "backgroundColor": "#d9eddf",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "16px 20px"
    },
    "bannerTipRed": {
      "backgroundColor": "#f7d6d3",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "16px 20px"
    },
    "bannerTipPurple": {
      "backgroundColor": "#e7d8ee",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "16px 20px"
    },
    "codeBlock": {
      "backgroundColor": "#23251d",
      "textColor": "#ffffff",
      "typography": {
        "fontFamily": "ui-monospace",
        "fontSize": "14px",
        "fontWeight": 400,
        "lineHeight": 1.43,
        "letterSpacing": 0
      },
      "rounded": "6px",
      "padding": "16px 20px"
    },
    "inlineCode": {
      "backgroundColor": "#e5e7e0",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "Source Code Pro",
        "fontSize": "14px",
        "fontWeight": 500,
        "lineHeight": 1.43,
        "letterSpacing": 0
      },
      "rounded": "2px",
      "padding": "2px 6px"
    },
    "primaryNav": {
      "backgroundColor": "#eeefe9",
      "textColor": "#23251d",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 600,
        "lineHeight": 1.5,
        "letterSpacing": 0
      },
      "rounded": "0px",
      "height": "56px"
    },
    "subNavStrip": {
      "backgroundColor": "#e5e7e0",
      "textColor": "#4d4f46",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 500,
        "lineHeight": 1.43,
        "letterSpacing": 0
      },
      "rounded": "0px",
      "height": "40px"
    },
    "docSidebar": {
      "backgroundColor": "#eeefe9",
      "textColor": "#4d4f46",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 500,
        "lineHeight": 1.43,
        "letterSpacing": 0
      },
      "rounded": "0px",
      "width": "240px"
    },
    "footerSection": {
      "backgroundColor": "#eeefe9",
      "textColor": "#4d4f46",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "14px",
        "fontWeight": 500,
        "lineHeight": 1.43,
        "letterSpacing": 0
      },
      "rounded": "0px",
      "padding": "32px 24px"
    },
    "linkInline": {
      "textColor": "#1078a3",
      "typography": {
        "fontFamily": "IBM Plex Sans Variable",
        "fontSize": "16px",
        "fontWeight": 400,
        "lineHeight": 1.5,
        "letterSpacing": 0
      }
    }
  },
  "PostHog's marketing system is built on the visual contradiction at the heart of the brand": "a serious open-source product analytics platform rendered as if it were a friendly engineering sketchbook. The chrome runs on a warm cream canvas (`#eeefe9` — `#eeefe9`) — not white — and every page is dotted with hand-drawn hedgehog mascots in lab coats, lounge chairs, terminals, and reading glasses, scattered across the layout like marginalia in a textbook. Type sits in IBM Plex Sans Variable at olive-gray (`#4d4f46` — `#4d4f46`) for body and deep olive-charcoal (`#23251d` — `#23251d`) for headlines, with weights stepped tightly between 400, 600, 700, and 800 to create hierarchy without color. The single saturated yellow-orange pill (`#f7a501` — `#f7a501`) is the brand's only loud chromatic moment; everything else is cream, olive, white card, and the occasional pastel callout band.",
  "The system has a distinctive **twoMode body layout**": "marketing pages (home, workflows, pricing) lean on alternating-pastel callout bands and feature tiles in white cards on cream, while documentation pages add a sticky 240px left sidebar with a rounded outline-icon section list. Code samples are full-width dark blocks on `#23251d` (the same olive-charcoal that carries body ink, used inverted) inside white doc cards, creating the system's most distinctive visual moment: a dark-on-dark code island floating inside a white card on a cream canvas, with a hedgehog mascot doodled in the margin.",
  "**Key Characteristics": "**",
  "- 4–8px radius card vocabulary": "`6px` (6px) for most components, `8px` (8px) for select containers, fully rounded for pill chips",
  "> **Source pages": "** `/` (home), `/pricing` (pricing detail), `/docs/product-analytics` (docs article), `/workflows` (product feature page). The chrome palette is identical across all four pages — only doc-specific accents (callout-banner pastels, code-block dark surface) appear exclusively inside the docs experience.",
  "- **PostHog Yellow** (`{colors.primary}` — `#f7a501`)": "the universal primary CTA. Sticky \"Get started — free\" pill in the top-right of every nav, hero CTAs, pricing-tier subscribe buttons, footer signup pill. The system's only saturated chromatic moment.",
  "- **Yellow Pressed** (`{colors.primaryPressed}` — `#dd9001`)": "pressed state for the primary pill.",
  "- **Yellow Active** (`{colors.primaryActive}` — `#b17816`)": "deeply-pressed yellow + the system's gold-toned border accent (rare 1px gold rule on inline form elements).",
  "- **Canvas** (`{colors.canvas}` — `#eeefe9`)": "the warm cream page background. End-to-end on every page; the brand's most distinctive surface choice.",
  "- **Soft Surface** (`{colors.surfaceSoft}` — `#e5e7e0`)": "button-secondary fill, sub-nav strip background, inline-code chip background.",
  "- **Surface Card** (`{colors.surfaceCard}` — `#ffffff`)": "true white card and tile background sitting on top of the cream canvas. The dominant card surface.",
  "- **Surface Doc** (`{colors.surfaceDoc}` — `#fcfcfa`)": "a faintly cream-warm white used inside doc article body cards — slightly softer than pure white to keep the page tonally unified.",
  "- **Surface Dark** (`{colors.surfaceDark}` — `#23251d`)": "the deep olive-charcoal used inverted as code-block background. The same hex as `#23251d` — the brand uses one olive-near-black for both text and dark code surfaces.",
  "- **Hairline** (`{colors.hairline}` — `#bfc1b7`)": "1px card border, table rule, footer column dividers.",
  "- **Hairline Soft** (`{colors.hairlineSoft}` — `#dcdfd2`)": "in-card row divider, soft inset rule.",
  "- **On Dark** (`{colors.onDark}` — `#ffffff`)": "primary text on `#23251d` code blocks.",
  "- **Ink** (`{colors.ink}` — `#23251d`)": "headlines, button text on light, primary nav links — deep olive-charcoal that reads near-black against cream.",
  "- **Body** (`{colors.body}` — `#4d4f46`)": "default paragraph text, doc article body, inline link color before hover. The brand's most-used text color.",
  "- **Charcoal** (`{colors.charcoal}` — `#33342d`)": "emphasized body text where body is too soft.",
  "- **Mute** (`{colors.mute}` — `#6c6e63`)": "metadata, footer link text, in-list secondary annotations.",
  "- **Ash** (`{colors.ash}` — `#9b9c92`)": "disabled-state text and lowest-emphasis utility.",
  "- **Stone** (`{colors.stone}` — `#b6b7af`)": "least-emphasis caption text and disabled icon color.",
  "- **Link Blue** (`{colors.linkBlue}` — `#1d4ed8`)": "inline anchor link inside body prose. The system's primary informational link color.",
  "- **Link Teal** (`{colors.linkTeal}` — `#1078a3`)": "doc-article inline link variant, paired with body text.",
  "- **Accent Blue** (`{colors.accentBlue}` — `#2c84e0`) + **Accent Blue Soft** (`{colors.accentBlueSoft}` — `#dceaf6`)": "\"💡 Tip / Info\" callout banner inside docs.",
  "- **Accent Red** (`{colors.accentRed}` — `#cd4239`) + **Accent Red Soft** (`{colors.accentRedSoft}` — `#f7d6d3`)": "\"⚠️ Warning / Caution\" callout banner.",
  "- **Accent Green** (`{colors.accentGreen}` — `#2c8c66`) + **Accent Green Soft** (`{colors.accentGreenSoft}` — `#d9eddf`)": "\"✅ Success / Positive\" callout banner.",
  "- **Accent Purple** (`{colors.accentPurple}` — `#7c44a6`) + **Accent Purple Soft** (`{colors.accentPurpleSoft}` — `#e7d8ee`)": "\"📘 Note / Reference\" callout banner.",
  "- **Focus Ring** (`{colors.focusRing}` — `rgba(59,130,246,0.5)`)": "translucent blue browser-default focus ring around interactive elements.",
  "The brandDistinctive choice is the **mixed weight ladder** (400 / 500 / 600 / 700 / 800) — most chrome lives in the 400–700 band, with weight 800 reserved exclusively for the larger display headlines on home and pricing. This gives the system its \"engineering blog\" feel": "hierarchy is built from weight contrast much more than from size.",
  "- **Base unit": "** 8px (with finer 2/4/6px steps for tight inline gaps in callout banners and pill buttons).",
  "- **Tokens (front matter)": "** `2px` (2px) · `4px` (4px) · `8px` (8px) · `12px` (12px) · `16px` (16px) · `24px` (24px) · `32px` (32px) · `80px` (80px).",
  "- **Universal section rhythm": "** every page in the set uses `80px` (80px) as the vertical gap between major content blocks. Card grids use `16px` (16px) gutters; card internal padding sits at `24px` (24px) for product cards and `32px` (32px) for pricing tier cards.",
  "- **Max width": "** ~1280px content area at desktop with 24px gutters (~48px at ultrawide). Doc article body sits at ~720px max width with the 240px sidebar pushing the article column right of center.",
  "- **Marketing card grid": "** 4-up → 3-up → 2-up → 1-up at 1024, 768, and 480px; gutters drop from 16px to 12px on mobile.",
  "- **Pricing tier grid": "** 3-up at desktop with a left rail of plan info, collapsing to 2-up + 1 at tablet and 1-up at mobile.",
  "- **Doc layout": "** desktop 240px sidebar + 720px article → tablet sidebar collapses to a top accordion → mobile fully collapsed accordion.",
  "- **Footer": "** 6-up link columns → 3-up at tablet → 2-up at mobile.",
  "Depth comes entirely from illustration and the pastel callout band system, not from CSS effects": {},
  "There is no photography. Visual elements are limited to": {},
  "- LowestEmphasis action": "\"See all docs →\", \"Browse all features\".",
  "- Default": "background `#ffffff`, text `#23251d`, 1px solid `#bfc1b7`, type `[object Object]`, padding `8px 12px`, height `36px`, rounded `6px`.",
  "- Active": "background flips to `#23251d`, text `#ffffff` — the chip flips fully inverted on selection.",
  "- Focused": "same surface; 2px solid `#2c84e0` border replaces the 1px hairline + a translucent `rgba(59,130,246,0.5)` outline.",
  "- Container": "background `#23251d` (deep olive-charcoal), text `#ffffff` in `[object Object]`, padding `16px 20px`, rounded `6px`.",
  "- Layout": "6-column horizontal link grid (Product · Resources · Company · Community · Pricing · Legal), each column with a `[object Object]` (uppercase) header and a vertical list of links in `[object Object]` `#4d4f46`.",
  "- Layout (desktop)": "PostHog wordmark + hedgehog logo at left, nav menu cluster (\"Pricing · Docs · Community · Company\"), right cluster with a search-glyph, \"Login\" link, and the always-yellow `{component.button-primary}` \"Get started — free\" pill anchored to the far right.",
  "- Bottom row": "PostHog wordmark + small hedgehog illustration, copyright in `[object Object]` `#6c6e63`, social-icon row at far-right.",
  "- **Primary nav": "** desktop horizontal cluster → tablet hamburger drawer at 768px. The yellow \"Get started — free\" CTA stays visible at every breakpoint.",
  "- **SubNav strip": "** desktop horizontal anchor row → tablet horizontal scroll → mobile select dropdown.",
  "- **Pricing grid": "** 3-up → 2+1 → 1-up stacked at tablet and below.",
  "- **Section padding": "** `80px` (80px) desktop → 64px tablet → 48px mobile.",
  "- **Hero headline": "** `[object Object]` (36px) at desktop, scaling to ~28px at mobile, line-height holding at 1.5.",
  "The only \"imagery\" in the system is handDrawn hedgehog illustrations rendered as inline SVG. They preserve their natural aspect at every breakpoint and scale via CSS `width": "auto; max-width: 100%`. There is no responsive art-direction needed because there is no photography.",
  "id": "posthog"
} as const;
export default theme;
