#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

// Small, dependency-free parser for the structured YAML subset used by DESIGN.md.
function scalar(value) {
  const v = value.trim();
  if (!v) return {};
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) return v.slice(1, -1);
  if (v === 'true' || v === 'false') return v === 'true';
  if (/^-?\d+(\.\d+)?$/.test(v)) return Number(v);
  return v;
}

function parseYaml(text) {
  const root = {};
  const stack = [{ indent: -1, value: root }];
  for (const raw of text.split(/\r?\n/)) {
    if (!raw.trim() || raw.trimStart().startsWith('#') || raw.trim() === '---') continue;
    const indent = raw.match(/^\s*/)[0].length;
    const match = raw.trim().match(/^([^:]+):(?:\s*(.*))?$/);
    if (!match) continue;
    const key = match[1].trim();
    const value = scalar(match[2] ?? '');
    while (stack.at(-1).indent >= indent) stack.pop();
    const parent = stack.at(-1).value;
    parent[key] = value;
    if (value && typeof value === 'object' && !Array.isArray(value)) stack.push({ indent, value });
  }
  return root;
}

function resolveRefs(value, root) {
  if (typeof value === 'string') {
    const exact = value.match(/^\{([^}]+)\}$/);
    const get = (p) => p.split('.').reduce((o, k) => o?.[k], root);
    if (exact) return get(exact[1]) ?? value;
    return value.replace(/\{([^}]+)\}/g, (_, p) => String(get(p) ?? `{${p}}`));
  }
  if (Array.isArray(value)) return value.map((v) => resolveRefs(v, root));
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveRefs(v, root)]));
  return value;
}

function camelizeKeys(value) {
  if (Array.isArray(value)) return value.map(camelizeKeys);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value).map(([key, child]) => [
    key.replace(/-([a-z])/g, (_, c) => c.toUpperCase()),
    camelizeKeys(child),
  ]));
}

const input = process.argv[2] || 'DESIGN.md';
const output = process.argv[3] || `App/themes/${path.basename(input, path.extname(input)).toLowerCase()}.ts`;
const parsed = parseYaml(fs.readFileSync(input, 'utf8'));
const theme = camelizeKeys(resolveRefs(parsed, parsed));
const name = String(theme.name || path.basename(input, path.extname(input))).replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase());
const id = path.basename(output, path.extname(output)).toLowerCase();
const content = `// Generated by scripts/extract-theme.mjs from ${input}.\nexport const theme = ${JSON.stringify({ ...theme, id }, null, 2)} as const;\nexport default theme;\n`;
fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, content);
console.log(`Extracted ${theme.name || name} -> ${output}`);
